# Generated by Django 3.2.8 on 2021-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20211124_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile-pictures'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='users',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('nurse', 'Nurse')], default='patient', max_length=10),
        ),
    ]
