# Generated by Django 3.2.8 on 2021-11-27 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20211127_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='users',
            new_name='user_type',
        ),
    ]
