# Generated by Django 3.2.8 on 2021-11-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='value',
            field=models.CharField(max_length=10),
        ),
    ]
